# FIXME: Remove this temporary test config!
plugins:
  - "./lib/plugins/settings-secrets"
  - "./lib/plugins/env"
  - "./lib/plugins/travis"
target:
  name: main
settings:
  settings-secrets:
    travis: true
